[2024-10-13T23:05:54.817+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-10-13T23:05:42.607806+00:00 [queued]>
[2024-10-13T23:05:54.823+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-10-13T23:05:42.607806+00:00 [queued]>
[2024-10-13T23:05:54.823+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-13T23:05:54.838+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-10-13 23:05:42.607806+00:00
[2024-10-13T23:05:54.867+0000] {standard_task_runner.py:57} INFO - Started process 52 to run task
[2024-10-13T23:05:54.872+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-10-13T23:05:42.607806+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpbxkf45i_']
[2024-10-13T23:05:54.874+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask s3_upload
[2024-10-13T23:05:54.942+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-10-13T23:05:42.607806+00:00 [running]> on host 90969c3d3705
[2024-10-13T23:05:55.039+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yunus Emre KORKMAZ' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T23:05:42.607806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T23:05:42.607806+00:00'
[2024-10-13T23:05:55.054+0000] {logging_mixin.py:151} INFO - 'S3FileSystem' object has no attribute 'exist'
[2024-10-13T23:05:55.055+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 9, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-10-13T23:05:55.063+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20241013T230542, start_date=20241013T230554, end_date=20241013T230555
[2024-10-13T23:05:55.076+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task s3_upload ('NoneType' object has no attribute 'split'; 52)
[2024-10-13T23:05:55.094+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-13T23:05:55.107+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
