[2024-10-13T15:22:27.297+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-10-13T15:22:25.301293+00:00 [queued]>
[2024-10-13T15:22:27.301+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-10-13T15:22:25.301293+00:00 [queued]>
[2024-10-13T15:22:27.301+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-13T15:22:27.489+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-10-13 15:22:25.301293+00:00
[2024-10-13T15:22:27.493+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2024-10-13T15:22:27.495+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-10-13T15:22:25.301293+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpdffvubv4']
[2024-10-13T15:22:27.497+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask reddit_extraction
[2024-10-13T15:22:27.520+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-10-13T15:22:25.301293+00:00 [running]> on host f28f66444a85
[2024-10-13T15:22:27.550+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yunus Emre KORKMAZ' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T15:22:25.301293+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T15:22:25.301293+00:00'
[2024-10-13T15:22:28.018+0000] {logging_mixin.py:151} INFO - connected to reddit!
[2024-10-13T15:22:29.262+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 9, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 29, in extract_posts
    post = {key:post_dict[key] for key in POST_FIELDS}
  File "/opt/airflow/etls/reddit_etl.py", line 29, in <dictcomp>
    post = {key:post_dict[key] for key in POST_FIELDS}
KeyError: 'self_textnum_comments'
[2024-10-13T15:22:29.270+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20241013T152225, start_date=20241013T152227, end_date=20241013T152229
[2024-10-13T15:22:29.278+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task reddit_extraction ('self_textnum_comments'; 62)
[2024-10-13T15:22:29.290+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-13T15:22:29.300+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
